### ISSUE TITLE
Make package-private and protected abstract classes and interfaces public to make Kotlin interop

### ISSUE THREAD

**Issue by goto1134** [optimatika/ojAlgo#237]
**Is your feature request related to a problem? Please describe.**
I'm using Kotlin for my work to use ojAlgo alongside with Ktor framework.
When I try to multiply two matrices I get IllegalAccessError
```
Exception in thread "main" java.lang.IllegalAccessError: tried to access class org.ojalgo.matrix.BasicMatrix from class ru.appmat.TestKt
	at ru.appmat.TestKt.main(test.kt:36)
	at ru.appmat.TestKt.main(test.kt)
```

This problem relates to a fundamental language-design issue https://youtrack.jetbrains.com/issue/KT-11700.
**Describe the solution you'd like**
Everything would work if you could **make** package-private and protected abstract classes and interfaces **public**.

**Comment by goto1134** [comment]
If it's ok for the project, I can make a PR

**Comment by apete** [comment]
It's certainly ok for you to create a PR.

Just don't spend too much time on it before presenting something to bring up a discussion. ojAlgo is primarily a Java library, but if some small change can improve compatibility with other JVM languages then why not.

I recently noticed a thread at stack overflow where a Clojure user had a similar (I believe) problem with ojAlgo. 

https://stackoverflow.com/questions/58968216/cannot-call-particular-java-method-from-clojure/58969526#58969526

As I understand it the actual problem is with Kotlin (and Clojure).

**Comment by apete** [comment]
Will keep this issue open until https://github.com/optimatika/ojAlgo/tree/KotlinInteroperability is merged with develop.

**Comment by apete** [comment]
I believe I'm done reviewing this now. Please verify if this (the develop branch) works for you.

**Comment by apete** [comment]
I have now released v48.1.0 that I hope works for you.

**Comment by goto1134** [comment]
Checked every scenario I had, everything works perfect. Sorry for a late reply

**Comment by apete** [comment]
good to know, thanks
