### ISSUE TITLE
Missing hardware profile

### ISSUE THREAD

**Issue by VitekVlcek-Broadcom** [optimatika/ojAlgo#260]
**Describe the bug**
When running matrix multiplication I get 
```
ojAlgo includes a small set of predefined hardware profiles,
none of which were deemed suitable for the hardware you're currently using.
A default hardware profile, that is perfectly usable, has been set for you.
You may want to set org.ojalgo.OjAlgoUtils.ENVIRONMENT to something that
better matches the hardware/OS/JVM you're running on, than the default.
Additionally it would be appreciated if you contribute your hardware profile:
https://github.com/optimatika/ojAlgo/issues
Architecture=s390x Threads=10 Memory=67108864
```

**Additional context**
I'm using it on IBM z hardware with IBM JVM 1.8.0. 
When I run my code I get the above message.
When I tried to limit the environment I did not receive better results.
Is there a tuning procedure I should run first to optimize environment?
I use `org.ojalgo:ojalgo:48.1.0`

**Comment by apete** [comment]
1) That message doesn't mean anything is broken. just perhaps not optimally tuned.

2) To get rid of the message you should create a hardware profile like those in `org.ojalgo.machine.Hardware`, call `virtualise`, and set the results to `org.ojalgo.OjAlgoUtils#ENVIRONMENT`. Alternatively you may set the system property shut.up.ojAlgo.

3) The default that is set for you now, should be ok to use. If you experience som performance issues it is most likely caused by something else. (Regardless of that please contribute a hardware profile for that machine you're running on.)
