### ISSUE TITLE
wrong status for solutions when optimization using IntegerSolver is aborted

### ISSUE THREAD

**Issue by pakkg** [optimatika/ojAlgo#310]
ojAlgo version 48.3.2

When an optimization is aborted, the status of the result is `INFEASIBLE`, whereas it might be feasible.

**To Reproduce**
* Two binary variables X and Y
* Constraint X + Y <= 1
* Function to maximize: X
* `iterations_abort` very low
* The optimization is aborted, then the result state should **not** be INFEASIBLE, since this problem is feasible.

**Test Case**
```java
@Test
public void testStatusForAbortedOptimization() {

  ExpressionsBasedModel model = new ExpressionsBasedModel();
  
  model.options.iterations_abort = 2;
  
  Variable varX = model.addVariable("X").binary();
  Variable varY = model.addVariable("Y").binary();
  
  // two possible solutions: X = 0, Y = 1 or X = 1, Y = 0
  Expression constraint =
    model
      .addExpression("X + Y <= 1")
      .upper(ONE)
      .set(varX, ONE)
      .set(varY, ONE);
  
  // function maximized by X = 1
  Expression objectiveFunction =
    model
      .addExpression("X")
      .weight(ONE)
      .set(varX, ONE);
  
  Result result = model.maximise();
  
  // the result provides a valid solution
  System.out.println("valid solution? " + model.validate(result));
  TestUtils.assertTrue(model.validate(result));
  
  // the result is in INFEASIBLE state, it should not be
  System.out.println("result state: " + result.getState());
  TestUtils.assertNotEquals(result.getState(), Optimisation.State.INFEASIBLE);
}
```

**Additional context**
The provided test case uses `iterations_abort`, but the same problem occurs with `time_abort`.

**Comment by apete** [comment]
The returned result is: `INFEASIBLE 0.0 @ { 0, 0 }`

The returned solution is `{ 0, 0 }` and since that is not a feasible solution the state is set to `INFEASIBLE`.

It seems the only problem is that 2 iterations is not enough, even in this simple case, to find a solution. If you allow 4 iterations the result is:

`OPTIMAL 1.0 @ { 1, 0 }`

For a MIP, in the general case, there is no way to know a problem/model is feasible before finding a feasible solution.

**Comment by pakkg** [comment]
The returned solution { 0, 0 } is a feasible solution, because 0 + 0 <= 1, so the status `INFEASIBLE` is unexpected. A status SUBOPTIMAL seems better.

The provided unit test checks this solution is correct, with the line `assertTrue(model.validate(result))`
.

**Comment by apete** [comment]
I checked what happens in this case again. 2 iterations simply isn't enough for anything to complete normally. The LP solver at the root node doesn't even find a feasible solution. 

{ 0, 0 } is just some default value for the solutions array and the fact that it happens to be feasible is just a coincidence.

I think the correct state to return in this case would be UNEXPLORED or possibly FAILED.

(Generally speaking it's better to set time limits rather than iteration limits.)
