### ISSUE TITLE
ojAlgo cannot solve large linear programs since version 41.0.0

### ISSUE THREAD

**Issue by hoangtungdinh** [optimatika/ojAlgo#32]
Hi,

I found that since version 41.0.0, ojAlgo cannot solve large linear programs (everything works fine in version 40.0.0).

You can do as follows to reproduce the issue:

Clone my repository
`git clone -b reproduce_ojalgo_issue https://github.com/hoangtungdinh/BeSwarm.git`
Run the following gradle task
`gradle reproduceOjAlgoIssue`

The gradle task will execute the following class: `io.github.hoangtungdinh.beswarm.solvers.profiler.OjSolverIssue`, which creates and solves 3 different linear programs (one small program, two big programs), using ojAlgo v40. All 3 linear programs are solved.

You then can change the version of ojAlgo in `build.gradle` to v41 and v42 and execute the gradle task again. Only the first linear program (the small one) is solved. OjAlgo cannot solve the last two linear programs.

As it is quite hard to see the linear program model in my code, I generated a .mps file for each model (using the export functionality from CPLEX). You can find them in my repository ([problem1](https://github.com/hoangtungdinh/BeSwarm/blob/reproduce_ojalgo_issue/problem1.mps), [problem2](https://github.com/hoangtungdinh/BeSwarm/blob/reproduce_ojalgo_issue/problem2.mps), [problem3](https://github.com/hoangtungdinh/BeSwarm/blob/reproduce_ojalgo_issue/problem3.mps))

Unfortunately, ojAlgo cannot read those files. My attempt to read those files can be found [here](https://github.com/hoangtungdinh/BeSwarm/blob/reproduce_ojalgo_issue/src/main/java/io/github/hoangtungdinh/beswarm/solvers/profiler/OjAlgoReadFromMps.java). The `MathProgSysModel` throws a `NumberFormatException`.

**Comment by apete** [comment]
I ran "reproduceOjAlgoIssue" and yes I see the fails, but other than that you example is not easily accessible to me. 

I modified the solve() method in OjModel to be:

  public boolean solve() {
    model.options.debug(LinearSolver.class);
    result = model.minimise();
    System.out.println(result.toString());
    return result.getState().isSuccess();
  }

That gave me a bit more info. (You can do that as well.)

Between v40 and v41 there were no changes to the LP solver, but a couple of things changed in ExpressionsBasedModel.

One change is related to rescaling of model parameters. Do you feed the model parameters larger than 1E16 or smaller than 1E-16 ? If you do the model parameter scaling feature is turned off as of v41.

The other change is some code in ExpressionsBasedModel to identity unbounded variables/models. Look into the identifyFixedVariables() method.

My guess is since your model is machine generated you end up with some very large or small model parameters, which turns off the parameter scaling feature and that doesn't work out for you. The relevant code is in OptimisationUtils#getAdjustmentExponent(double,double).

If you can verify this is the problem I'll review that code to see how it can be improved.

Internally ExpressionsBasedModel stores model parameters as BigDecimal. It is best for you if you actually input them as BigDecimal, and that you actually think about what precision and scale you want those numbers to have.

**Comment by hoangtungdinh** [comment]
Hi,

It turns out that I accidentally created some unbounded variable by:

```
final Variable variable =
        Variable.make(String.valueOf(index)).lower(-Double.MAX_VALUE).upper(Double.MAX_VALUE);
```

instead of just:

```
final Variable variable =
        Variable.make(String.valueOf(index));
```

So, yes, there are some model parameters were larger than 1E6. After I removed the Double.MAX_VALUE, everything works fine again.

**Comment by apete** [comment]
Just checked in some minor changes to how extremely large parameters (like Double.MAX_VALUE) are handled. I believe with these changes you would not have noticed any problems when upgrading from v40. If possible please verify that this works.

I recommend building your model using BigDecimal. Whatever number type you use it will be converted to BigDecimal internally. It's better you do that conversion yourself so that you can specify the precision and scale. (And you should really think about what the precision and scale should be, you build better models that way.)

When/if you think this issue is resolved then please close it.

**Comment by hoangtungdinh** [comment]
I confirm that the commit 7b7a74958af3168e173ccd0595b2b86815df4b49 solves the problem.

Thanks for your recommendation about using BigDecimal.
