### ISSUE TITLE
Java 16 SIMD Support

### ISSUE THREAD

**Issue by eix128** [optimatika/ojAlgo#350]
Hi ,
Java 16 has released Vector API

You can look at the links for details:
https://metebalci.com/blog/what-is-new-in-java-16/
https://openjdk.java.net/jeps/338

Java 16's SIMD API has intrinsic capability.
Much faster then JNI.That directly converts these method calls to ARM NEON or AVX512 etc..

It will be good to fit OJALGO to new Java 16's Vector API

**Comment by apete** [comment]
Hi, yes, this is of course interesting for a library like ojAlgo. Currently not sure when/how to support it. Since a majority of Java systems still run on Java 8 we'd have to maintain 2 branches. Moving in that direction. Just not very fast at this point.

The really big change will be when project Valhalla is released.

**Comment by eix128** [comment]
Yes true.
You can also checkout
https://github.com/beehive-lab/TornadoVM

TornadoVM lets any java loop to utilize GPU by just annotation.
But maybe with bad optimization

**Comment by apete** [comment]
Wasn't aware of what TornadoVM is – cool.

ojAlgo is strictly for the JVM with zero dependencies. Could be interesting to support something like TornadoVM, or simply using native code, via some sort of plugin functionality. Most likely ojAlgo will focus on the VectorAPI, project Valhalla and optimising for standard JVM:s.
