### ISSUE TITLE
INFEASIBLE for linear program, should be DISTINCT

### ISSUE THREAD

**Issue by flaghacker** [optimatika/ojAlgo#61]
Run the following code:

```java
Variable x = Variable.make("x").lower(0);
Variable y = Variable.make("y").lower(0);

ExpressionsBasedModel model = new ExpressionsBasedModel();
model.addVariable(x);
model.addVariable(y);

model.addExpression("first").set(x, 2).set(y, 3).upper(1);
model.addExpression("second").set(x, -2).set(y, 3).lower(1);

Optimisation.Result result = model.maximise();
System.out.println(result);
```

The output is

``INFEASIBLE 0.0 @ [0.0, 0.3333333333333333]``

But the problem is actually feasible, the solution [0, 1/3] respects both constraints. The output should be

``DISTINCT 0.0 @ [0.0, 0.3333333333333333]``

I'm not sure what went wrong, maybe the precision isn't good enough? Is there a way to get the solver to run on rational numbers instead of `BigDecimal`?

**Comment by apete** [comment]
Seems to be a problem with (one of) the model presolvers. The model is never actually sent to the LP solver. Somehow the model presolvers conclude that the upper limit of x is -5E-35, and that means the model is infeasible because the lower limit is 0.0.

ExpressionsBasedModel internally works with BigDecimal and the solvers with double. This can't be changed/configured.

I'll get back to you when I found which presolver misbehaves.

If you `   ExpressionsBasedModel.clearPresolvers();`  the model will solve correctly.

**Comment by flaghacker** [comment]
Thanks for the quick reply!

After clearing the output is now `OPTIMAL 0.0 @ [0.0, 0.333333333333]`, still not exactly correct

**Comment by apete** [comment]
I believe that presolver is fixed now.

Please close this issue when you verified that the problem is solved.

**Comment by flaghacker** [comment]
Both #61 and #62 are fixed now, thanks a lot for the quick replies!
