### ISSUE TITLE
UNBOUNDED but should be INFEASIBLE

### ISSUE THREAD

**Issue by flaghacker** [optimatika/ojAlgo#69]
Run the following code:

```java
Variable x = Variable.make("x").lower(0).weight(3);
Variable y = Variable.make("y").lower(0).weight(2);
Variable z = Variable.make("z").lower(0).weight(-2);

ExpressionsBasedModel model = new ExpressionsBasedModel();
model.addVariable(x);
model.addVariable(y);
model.addVariable(z);

model.addExpression().set(x, 0).set(y, 1).set(z, -2).level(4);
model.addExpression().set(x, 0).set(y, 4).set(z, -2).upper(1);

Optimisation.Result solution = model.maximise();
System.out.println(solution);
```

The output is `UNBOUNDED 23.0 @ [0.0, 19.0, 7.5]`, but I think the problem is actually infeasible: from `y - 2z = 4`  follows `y = 4 + 2z` and substituting that in the second constraint gives `4(4 + 2z) - 2z <= 1` and so `16 + 6z <= 1` and `z <= -15/6` which conflicts with `z >= 0`.

**Comment by apete** [comment]
There is no feasible combination of y and z.

x is not linked to to y or z, and x is unbounded.

The presolver finds that x is unbounded "first", and stops investigating feasibility.

Theoretically it is possible to find and return a feasible solution to an unbounded problem, but this doesn't seem like a serious problem. 

I'll see if this is easy to fix...

**Comment by apete** [comment]
The presolver is not able to conclude that the model (y and z combination) is infeasible, but it does conclude that x is unbounded.

The solver determines infeasibility without problem, but since the model already determined that it's unbounded the solver is never invoked.

I thought I'd be able to have the model determine infeasibility, but have not succeeded. The only option is to invoke the solver even if the model has been determined to be unbounded in some variable. That would give you the "correct" State.

**Comment by flaghacker** [comment]
I see. Thanks for taking a look at it!

**Comment by flaghacker** [comment]
Is his going to be fixed or will I have to disable the presolvers when I use the library if I want this functionality?

**Comment by apete** [comment]
I pushed a solution/workaround.

The way Optimisation.State is defined UNBOUNDED cannot be paired with an infeasible solution. So I had to change something.

Some solvers, depending on the implemeneted algorithm, cannot differentiate between unbounded and infeasible. CPLEX (and Gurobi) for instance may return a solution status "InfeasibleOrUnbounded".

**Comment by flaghacker** [comment]
It does work now, thanks again!
