### ISSUE TITLE
Move to junit5 and fix test problems

### ISSUE THREAD

**Issue by apete** [optimatika/ojAlgo#75]
The ojAlgo junit tests are essentially still junit3 tests. It's time to upgrade. There are also a couple of concrete tests related problems:

- Travis currently doesn't run all tests, apparently due to some name convention mismatch related to using junit3/4.
- There are tests that sometimes fail because of randomly generated input, some tests take very long, some require network access to run. The tests need to be categorised (junit5 lets you you this) so that one can define a subset of the tests that always should pass, quickly even with no network access.
- Due to the above, there are tests that are permanently turned off. These should be turned on but appropriately categorised.
- The tests with random input should be refactored so that when/if they fail they will output the specific input used so that it is possible to then create test case for precisely that.
- Any other improvements you can think of?

**Comment by flaghacker** [comment]
Perhaps it would be possible to set the seed for the random tests to make them fully reproducible?

**Comment by apete** [comment]
That could definitely be the solution many of the test cases.

I'm guessing some tests related to random number generation, probability distributions or stochastic process may need a different solution.

To some extent I like the random input tests - more than once have they indicated problems I wouldn't have found otherwise. They can be seen as test case generators, but then they really need a mechanism to log/document the input that caused the failure.

**Comment by alf239** [comment]
I did use the logging in #74; it helps a lot with simple types, but, unfortunately, itdoes not really help with, say, matrices.

If you take a look at [Quickcheck](http://www.cse.chalmers.se/~rjmh/QuickCheck/manual.html) for example, it does a very interesting thing: after falsifying a property, it tries to shrink the parameters and find a _simple_ case that would still break the property. When it works, it's amazing. When it doesn't, it's not any worse that any other test.

As for fixing the seed, the problem is, it's a fragile approach: you take one more value here or there, and your test change again. It's good as it's reproducible, indeed, but when you start changing things around you still get the unrelated issues jumping at you.

The "ideal" test framework would use parameter generation - and whenever a property is falsified, generate a code to be cut-n-pasted into the test suite. This way, you get all the benefits of randomized property-based testing, and whenever you need reproducible results for the corner cases already found, you don't need to spend time handcrafting the test case.

**Comment by alf239** [comment]
Prepared PR #81 covering the JUnit 5 migration. I'm somewhat lost regarding the actual usage of tags, but it seem that if we set up filters in Maven properly, we can remove `@Ignore` from many multi-hour tests.

**Comment by alf239** [comment]
But the timing, etc. will require much more knowledge than what I posess right now, so someone else will need to add tags here and there.

**Comment by apete** [comment]
I think this is done. (re)tagging and fixing of individual tests should have specific issues, if necessary.
